### ISSUE TITLE
[metaissue] Colima does not follow semver properly

### ISSUE THREAD

**Issue by regulskimichal** [abiosoft/colima#908]
### Description

Colima version numbers are represented in such a way they suggest they follow [Semantic Versioning](https://semver.org). Unfortunately, recent changes were released as patches even though they break the compatibility with already existing VMs. Generally, it’s a good idea to group breaking changes into a single release since it requires less attention and manual actions from the users. Following semversions provides a general sense for users what kind of changes are introduced between releases.

### Operating System

- [ ] macOS Intel <= 13 (Ventura)
- [ ] macOS Intel >= 14 (Sonoma)
- [ ] Apple Silicon <= 13 (Ventura)
- [ ] Apple Silicon >= 14 (Sonoma)
- [ ] Linux

### Reproduction Steps

1.
2.
3.

**Comment by AndreasA** [comment]
strictly speaking semver behaves a bit differently below the 1.0 version. but it should still be non breaking inside a minor version like 0.6 which was not the case with 0.6 becasue from 0.6.1 to 0.6.5 delete and prune was necessary.
